name: appdelicia_flutter
description: Migración AppDelicia a Flutter (scaffold funcional)
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cached_network_image: ^3.2.4 # opcional si algunas imágenes están remotas en un futuro
  firebase_core: ^3.6.0        # ← ACTUALIZAR
  cloud_firestore: ^5.4.4      # ← ACTUALIZAR
  firebase_auth: ^5.3.1        # ← ACTUALIZAR
  intl: ^0.19.0
  pdf: ^3.10.4              # ← NUEVO: Para generar PDFs
  printing: ^5.11.0         # ← NUEVO: Para descargar/compartir PDFs
  path_provider: ^2.1.1     # ← NUEVO: Para guardar archivos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#E91E63"